name: Trigger auto deployment for container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-AutoDeployTrigger-109a623f-1b25-4900-9205-d02f3afa4fce.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: hub.docker.com
          username: ${{ secrets.CONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hub.docker.com/container-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app -g DefaultResourceGroup-EAU --server hub.docker.com --username  ${{ secrets.CONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n container-app -g DefaultResourceGroup-EAU --image hub.docker.com/container-app:${{ github.sha }}
